package com.tazzzo.catalog.consumer;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * LIST-CURSOR-1 signing configuration. {@code tazzzo.consumer.cursor-hmac-key-b64} — the
 * Base64 of at least 32 random bytes. NO DEFAULT BY DESIGN: the production value is a deployment
 * secret generated by the CEO/deployment setup, never invented here, and never checked in. When it
 * is missing or malformed the LIST route fails closed (503) before any product work; ROOT and
 * CHILDREN do not need it.
 */
@ConfigurationProperties(prefix = "tazzzo.consumer")
public class ConsumerCursorProperties {

    private String cursorHmacKeyB64;

    public String getCursorHmacKeyB64() {
        return cursorHmacKeyB64;
    }

    public void setCursorHmacKeyB64(String cursorHmacKeyB64) {
        this.cursorHmacKeyB64 = cursorHmacKeyB64;
    }
}
