package com.tazzzo.inventory;

import java.time.Instant;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * PR-14A — a request to reserve stock for one order, all-or-nothing, across one or more SKUs at
 * ONE fulfillment location. {@code reservationId} and {@code expiresAt} are generated by the
 * CALLER before any transaction begins (never inside {@link InventoryReservationService}'s
 * session-aware methods), so a driver retry of the same logical call reuses the identical values —
 * the {@link Tx} multiple-invocation contract this whole module already follows elsewhere.
 *
 * <p>Bounded like Cart's own item limit (50 distinct SKUs) — the same "cart-sized" order of
 * magnitude applies here, and there is no reason a reservation would ever need to be larger than
 * the order that produced it.
 */
public record InventoryReservationCommand(String orderId, String fulfillmentLocationId,
                                          List<InventoryReservationItem> items,
                                          InventoryReservationId reservationId, Instant expiresAt) {

    static final int MAX_DISTINCT_ITEMS = 50;

    public InventoryReservationCommand {
        if (orderId == null || orderId.isBlank()) {
            throw new IllegalArgumentException("orderId required");
        }
        if (fulfillmentLocationId == null || fulfillmentLocationId.isBlank()) {
            throw new IllegalArgumentException("fulfillmentLocationId required");
        }
        if (items == null || items.isEmpty()) {
            throw new IllegalArgumentException("items must be non-empty");
        }
        if (items.size() > MAX_DISTINCT_ITEMS) {
            throw new IllegalArgumentException("items exceeds the limit of " + MAX_DISTINCT_ITEMS);
        }
        Set<String> seen = new HashSet<>();
        for (InventoryReservationItem item : items) {
            if (!seen.add(item.skuId())) {
                throw new IllegalArgumentException("duplicate skuId in reservation command: " + item.skuId());
            }
        }
        items = List.copyOf(items);
        if (reservationId == null) {
            throw new IllegalArgumentException("reservationId required");
        }
        if (expiresAt == null) {
            throw new IllegalArgumentException("expiresAt required");
        }
    }

    /**
     * PR-14A — the canonical, order-independent fingerprint the fingerprint hash is built from:
     * items sorted by skuId, so the client's original request ordering can never change identity.
     * {@code fingerprintVersion} is a manual tag ("v1") — bump it, never overload its meaning, if a
     * future field becomes meaning-bearing (documented on {@link InventoryReservationService}).
     */
    String canonicalFingerprintInput(String fingerprintVersion) {
        StringBuilder sb = new StringBuilder(fingerprintVersion).append('|').append(orderId).append('|')
                .append(fulfillmentLocationId);
        items.stream().sorted(java.util.Comparator.comparing(InventoryReservationItem::skuId))
                .forEach(i -> sb.append('|').append(i.skuId()).append(':').append(i.quantity()));
        return sb.toString();
    }
}
